"""Determinism + freshness of the shock/herding sensitivity artifact (IMP-C04).

The artifact (``reports/shock_herding_sensitivity.md`` /
``.csv``) is generated by ``reports/generate_shock_herding_sensitivity.py``
against the canonical fixture with no RNG anywhere in the pipeline, so two
runs must produce byte-identical CSV output. The committed markdown also
records a config hash; regenerating must reproduce the current config's hash
(a stale committed artifact — one that no longer matches
``shock_params.yaml`` + ``herding_groups.yaml`` — is the negative-constraint
CI should catch, exercised here at the test level).
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

_MODULE_ROOT = Path(__file__).resolve().parents[1]
_REPORTS_DIR = _MODULE_ROOT / "reports"


def _import_generator():  # type: ignore[no-untyped-def]
    if str(_REPORTS_DIR) not in sys.path:
        sys.path.insert(0, str(_REPORTS_DIR))
    return importlib.import_module("generate_shock_herding_sensitivity")


def test_sensitivity_script_is_deterministic(tmp_path: Path) -> None:
    gen = _import_generator()
    rows = gen._load_canonical_rows()
    baseline_params = gen.load_shock_params()
    baseline_herding = gen.load_herding_config()

    a = gen._threshold_param_sensitivity(rows, baseline_params)
    b = gen._threshold_param_sensitivity(rows, baseline_params)
    assert a == b

    ha = gen._herding_cell_sensitivity(rows, baseline_herding)
    hb = gen._herding_cell_sensitivity(rows, baseline_herding)
    assert ha == hb


def test_committed_artifact_hash_matches_current_config() -> None:
    """The committed markdown's recorded config hash must match the live config.

    If this fails, someone changed shock_params.yaml or herding_groups.yaml
    without regenerating the sensitivity artifact — a stale sensitivity table
    is treated as no sensitivity table (IMP-C04 negative constraint).
    """
    gen = _import_generator()
    md_path = _REPORTS_DIR / "shock_herding_sensitivity.md"
    assert md_path.exists(), "run generate_shock_herding_sensitivity.py to create the artifact"
    text = md_path.read_text(encoding="utf-8")
    current_hash = gen._config_hash()
    assert current_hash in text, (
        "shock_herding_sensitivity.md's recorded config hash does not match the current "
        "shock_params.yaml + herding_groups.yaml — regenerate via "
        "generate_shock_herding_sensitivity.py"
    )


def test_generator_produces_both_artifacts(tmp_path: Path, monkeypatch) -> None:  # type: ignore[no-untyped-def]
    gen = _import_generator()
    out_md = tmp_path / "out.md"
    out_csv = tmp_path / "out.csv"
    monkeypatch.setattr(gen, "OUT_MD", out_md)
    monkeypatch.setattr(gen, "OUT_CSV", out_csv)
    rc = gen.main()
    assert rc == 0
    assert out_md.exists()
    assert out_csv.exists()
    assert "assignment-critical" in out_md.read_text(encoding="utf-8")
