"""Transparency scorer: phi in (0, 1] from ficha + methodological disclosure pillars.

**Calibration status (IMP-C02 / audit C4, C6):** every constant below
(``base`` in :func:`compute_phi_transparency`, ``step``, ``PHI_MIN``,
``PHI_MISSING_TWO_OR_MORE``) is a documented modeling **heuristic**, not a
value fit against a historical poll-vs-outcome residual dataset. ``phi``
directly sets ``sigma_obs`` (``models/tracking/hierarchical.py:observation_sigma``),
so this heuristic sets the width of every published credible interval. Per
IMP-C02's acceptance criteria, since these constants are not refit against
realized poll accuracy, the exposure is bounded instead by a published
sensitivity analysis:
``module_c_forecasting_scenarios/reports/phi_sensitivity.md`` (generated by
``reports/generate_phi_sensitivity.py``) tabulates ``sigma_obs(phi)`` under
+/-20%/+/-50% perturbation of ``base``/``step`` at every disclosure-pillar
count, and reports the resulting posterior-summary delta at ``MC_FAST``
fidelity. See ``METHODOLOGY.md`` § Transparency Proxy φ and Observation-Noise
Calibration for the full writeup. Reproducibility: these constants are
literals checked into this module (not computed at runtime from a mutable
dataset), so seed-42 reruns remain deterministic.
"""

from __future__ import annotations

PHI_MIN: float = 0.08
PHI_MAX: float = 1.0
PHI_MISSING_TWO_OR_MORE: float = 0.12


def compute_phi_transparency(
    has_ficha: bool,
    sample_size_known: bool,
    field_window_known: bool,
    mode_known: bool,
) -> float:
    """Transparency index ``phi`` in ``[PHI_MIN, PHI_MAX]`` from disclosure pillars.

    **Calibration status:** a documented modeling heuristic (see module
    docstring), not fit against a historical poll-accuracy dataset. See
    ``module_c_forecasting_scenarios/reports/phi_sensitivity.md`` for the
    published sensitivity bound on the resulting ``sigma_obs``/HDI-width
    exposure (IMP-C02 / audit C4, C6).

    Args:
        has_ficha: Whether the poll disclosed a methodological "ficha
            técnica" (technical sheet).
        sample_size_known: Whether the sample size is disclosed.
        field_window_known: Whether the field window (start/end dates) is
            disclosed.
        mode_known: Whether the survey mode (phone/in-person/online) is
            disclosed.

    Returns:
        ``phi`` in ``[PHI_MIN, PHI_MAX]`` — higher means more transparent.

    Raises:
        None.

    Example:
        >>> compute_phi_transparency(True, True, True, True)
        1.0
        >>> compute_phi_transparency(False, False, False, False)
        0.12
    """
    pillars = (sample_size_known, field_window_known, mode_known)
    n_ok = sum(1 for p in pillars if p)
    base = 0.55 if not has_ficha else 0.85
    step = 0.12
    phi = base + step * n_ok
    if n_ok <= 1:
        phi = min(phi, PHI_MISSING_TWO_OR_MORE + 0.25)
    if n_ok == 0:
        phi = PHI_MISSING_TWO_OR_MORE
    return float(max(PHI_MIN, min(PHI_MAX, phi)))


def compute_tau_eff(phi: float, tau_base: float = 1.0) -> float:
    """Effective precision ``tau_eff = max(1e-6, phi * tau_base)``.

    Args:
        phi: Transparency index (see :func:`compute_phi_transparency`).
        tau_base: Base precision scale before the transparency discount.

    Returns:
        The effective precision, floored at ``1e-6`` to stay strictly
        positive.

    Raises:
        None.

    Example:
        >>> compute_tau_eff(0.5, tau_base=2.0)
        1.0
    """
    return float(max(1e-6, phi * tau_base))
